name: release-win

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master

      - name: Get Zig version
        id: zig_version
        run: echo "zig_version=$(zig version)" >> $GITHUB_OUTPUT

      - run: zig env

      - name: Run zig fmt
        run: zig fmt --check .

      - name: Build
        run: zig build

      - name: Get ZLS version and mimimum build version
        id: zls_version
        run: |
          echo "zls_version=$(./zig-out/bin/zls --version)" >> $GITHUB_OUTPUT
          echo "zls_minimum_build_version=$(./zig-out/bin/zls --minimum-build-version)" >> $GITHUB_OUTPUT

      - name: Upload x86_64-windows artifact
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: actions/upload-artifact@v3
        with:
          name: zls-x86_64-windows
          path: artifacts/${{ steps.zls_version.outputs.zls_version }}/x86_64-windows/
